Cambiar "requireCordovaModule" por "require"
ERROR: Using "requireCordovaModule" to load non-cordova module "fs" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.